# Generated by Django 3.2.16 on 2024-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
